# Change these first
owner: RainThings # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: RSOS服务控制面板
    url: https://$US_SITE
  - name: HK区服
    url: https://$HK_SERVER
  - name: US区服
    url: https://$US_SERVER
  - name: RU区服
    url: https://$RU_SERVER

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  #  the baseUrl line if you don't have a custom domain and add your repo name there
  cname: status.ano404.top
  # baseUrl: /uptime
  logoUrl: https://cdn.jsdelivr.net/gh/RainThings/uptime/icon.svg
  name: Upptime
  introTitle: RSOS服务集群状态监控
  introMessage: 此页面负责展示系统运行状况，感谢您使用RSOS，本站还另外提供更新较慢的 [镜像站点](https://ol.ano404.top) 。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://cdn.jsdelivr.net/gh/$OWNER/$REPO
i18n:
  url: URL
  status: 状态
  history: 历史
  up: 正常
  degraded: 较差
  down: 离线
  responseTimeGraphAlt: 响应时间趋势
  ms: ms
  responseTime: 响应时间
  responseTimeDay: 24小时响应时间
  responseTimeWeek: 7天响应时间
  responseTimeMonth: 30天响应时间
  responseTimeYear: 1年响应时间
  uptime: 可用率
  uptimeDay: 4小时可用率
  uptimeWeek: 7日可用率
  uptimeMonth: 30日可用率
  uptimeYear: 1年可用率
  liveStatus: 实时状态
  liveStatusHtmlComment: ""
  allSystemsOperational: 🟩 好耶，系统全功率运转中~
  degradedPerformance: 🟨 啊咧，系统可用率偏低……
  completeOutage: 🟥 出大问题，全线系统均已宕机！
  partialOutage: 🟧 糟糕，部分系统宕机中……
  activeIncidents: 正在发生的事件
  incidentReport: "事故报告 #$NUMBER →"
  activeIncidentSummary: 自 $DATE 起 $POSTS 条相关动态
  incidentTitle: 事件详情 $NUMBER
  incidentDetails: 事件详情
  incidentFixed: 已修复
  incidentOngoing: 宕机中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentSubscribe: 订阅处理进展
  incidentViewOnGitHub: 在 GitHub 查看
  incidentCommentSummary: $AUTHOR 于 $DATE 发布
  incidentBack: ← 返回事件列表
  pastIncidents: 已处理的事件
  pastIncidentsResolved: 已于 $MINUTES 分钟内解决，共 $POSTS 条动态
  overallUptime: "总体运行状态: $UPTIME"
  overallUptimeTitle: 总体运行状态
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应
  sevelDayResponseTime: 7天响应时间
  responseTimeMs: 响应时间 (毫秒)
  loading: 加载中
  navGitHub: GitHub
  footer: Powered by [Upptime](https://upptime.js.org) and RainThings
  rateLimitExceededTitle: 频率受限
  rateLimitExceededIntro: 您已达到请求数上限，因此您可能需要尝试在一个小时后再次访问。或者，您可以添加 GitHub 个人访问令牌以继续使用此网站。
  rateLimitExceededWhatDoesErrorMean: 这个报错意味着什么？
  rateLimitExceededErrorMeaning: 我们使用 GitHub API 获取实时数据。默认情况下，GitHub 允许每个 IP 地址每小时 60 个请求，您已经达到了使用上限。
  rateLimitExceededErrorHowCanFix: 我如何处理它？
  rateLimitExceededErrorFix: 您可以稍等一小时，您的 IP 地址限制将恢复。或者，您可以添加您的 GitHub 个人访问令牌，这将使您获得每小时 5000 个请求的上限。
  rateLimitExceededGeneratePAT: 了解如何生成个人访问令牌
  rateLimitExceededHasSet: 您已配置个人访问令牌。
  rateLimitExceededRemoveToken: 移除令牌
  rateLimitExceededGitHubPAT: GitHub 个人访问令牌
  rateLimitExceededCopyPastePAT: 复制并粘贴您的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 哎呀，出大问题
  errorIntro: 暂时无法获取最新的状态数据……
  errorText: 如果您位于中国大陆，则可能是无法访问 GitHub 数据导致的。您也可以稍后再试或使用镜像网站ol.ano404.top。
  errorHome: 回到首页
  pastScheduledMaintenance: 已完成的定期维护
  scheduledMaintenance: 定期维护
  scheduledMaintenanceSummaryStarted: 已于 $DURATION 分钟前($DATE)开始
  scheduledMaintenanceSummaryStarts: 开始于 $DURATION 分钟前($DATE)
  startedAt: 已开始于
  startsAt: 开始于
  duration: 历时
  durationMin: $DURATION 分钟
  incidentCompleted: 完成
  incidentScheduled: 排队


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
